[package]
name = "areoxide"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.7.3", features = ["full"] }
reqwest = "0.12.9"
serde = "1.0.215"
serde_derive = "1.0.215"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["rt", "macros"] }
wasm-bindgen = "0.2"
